#!/bin/bash

git_ver=`git --version | grep -Eo "\s([0-9])\.([0-9])" | tr -d ' '`
curr=`echo ${git_ver} - 1.8 | bc`

if [[ ${curr} -lt 0 ]]
then
    git branch --set-upstream `git rev-parse --abbrev-ref HEAD` "${1}"
else
    git branch --set-upstream-to "remotes/${1}" `git rev-parse --abbrev-ref HEAD`
fi
