#!/bin/sh

lock() {
    ## Take a screenshot
    scrot /tmp/screen_locked.png
    #
    ## Pixellate it 10x
    mogrify -scale 10% -scale 1000% /tmp/screen_locked.png
    #
    ## Lock screen displaying this image.
    i3lock -i /tmp/screen_locked.png
    #
    ## Turn the screen off after a delay.
    sleep 60; pgrep i3lock && xset dpms force off
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0

