#!/bin/bash

currentApp=$1
currentDir=$2
currentShell=$(basename ${SHELL})

dirName=$(echo "${currentDir%/*}" | sed "s:${HOME}:~:" | sed -e "s;\(/.\)[^/]*;\1;g")/$(basename ${currentDir})

if [ "${currentApp}" = "${currentShell}" ]; then
    displayName="${dirName}"
elif [ "${dirName}" = "~" ]; then
    displayName="${currentApp}"
else
    displayName="${currentApp} - ${dirName}"
fi

echo "${displayName}"

